from ortools.linear_solver import pywraplp
def TP1_Exo2():
    solver = pywraplp.Solver('TP1_Exo2', pywraplp.Solver.CBC_MIXED_INTEGER_PROGRAMMING)
    infinity = solver.infinity()

    x = solver.IntVar(0.0, infinity, 'x')
    y = solver.IntVar(0.0, infinity, 'y')
    print('Number of variables =', solver.NumVariables())
    objective = solver.Objective()
    objective.SetCoefficient(x, 6)
    objective.SetCoefficient(y, 5)
    objective.SetMaximization()
    ct1 = solver.Constraint(-infinity, 7, 'ct1')
    ct1.SetCoefficient(x, 1)
    ct1.SetCoefficient(y, 3)
    ct2 = solver.Constraint(-infinity, 9, 'ct2')
    ct2.SetCoefficient(x, 3)
    ct2.SetCoefficient(y, 2)
    print('Number of constraints =', solver.NumConstraints())
    solver.Solve()
    print('Solution:')
    print('Valeur optimale =', solver.Objective().Value())
    print('x =', x.solution_value())
    print('y =', y.solution_value())
    print('Advanced usage:')
    print('Problem solved in %f milliseconds' % solver.wall_time())
    print('Problem solved in %d iterations' % solver.iterations())
    print('Problem solved in %d branch-and-bound nodes' % solver.nodes())
TP1_Exo2()